### ISSUE TITLE
Add support for flags that alter the world in a way that depends on the seed

### ISSUE THREAD

**Issue by kbranch** [kbranch/Magpie#1]
Flags that alter the world in a consistent way like dungeon dive should already work fine, but things like ER, random start location and boss shuffle need input from the user about what was put where.

Challenges:
- Understand how entrances and bosses are represented in logic
- Figure out how to populate the WorldSetup object appropriately
- Figure out how the UI should work

**Comment by kbranch** [comment]
Ideas for full ER:
- Make a table of connectors and their requirements both for traversal and checks
- Use table to make a connector picker that groups connectors by their obstacles/checks and shows the user screenshots of each entrance
- Instead of asking the user to connect both ends manually, let the user choose between:
  - "Leads to..." - click on the entrance you came out the other side at. Need to consider how to ask about one way connectors. Ask if there was a check left behind - if so, use connector picker to ask what stopped them. (have a separate connector picker for checks that lists screenshots of the checks? Maybe not, it still matters which entrance you came in sometimes)
  - "Dead ends at..." - Use connector picker to ask what stopped you

- Show full entrance chain hovered entrance is in
- The outsides of many connectors are pretty simple connectors themselves - make a map of how exterior connectors connect, similar to the existing interior map

**Comment by kbranch** [comment]
The only thing left here is the boss/miniboss randomization. The main challenge is figuring out a nice UI for it, populating WorldSetup isn't hard.

**Comment by kbranch** [comment]
I finally had a good idea for how to handle boss/miniboss shuffle:
 - Add a special type of node for bosses, styled based on the boss represented
 - Right click to select a different boss/miniboss
 - Do not include shuffle settings - just default to vanilla and let the user change if they want

**Comment by foxsouns** [comment]
that sounds good, but do ensure it works with entrance randomizer as well, ie: the boss type is listed with whatever location the dungeon is at. also locations in the actual dungeon; color dungeon and d8 have 2 miniboss locations, and dont forget moblin cave.
