### ISSUE TITLE
[Feature Request]: visible items indicator/pre-obtained check setting

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#13]
It would be helpful to add a sort of system to rightclick a check and set it to a specific item: for things like Mountain Access (I think?) that show you an item without allowing you to collect it, or rupee rewards that you do not want at the moment (due to hitting the cap), but want later.

**Comment by kbranch** [comment]
Sounds like a good idea, thanks! I'll need to think about how best to do this behind the scenes.

**Comment by foxsouns** [comment]
As an added: I think it should be an option for all, for those who save-scum/save-state, or those who just want to throw in a few locations from the spoiler, or something.

**Comment by kbranch** [comment]
Yeah, that makes sense - you could have the option of loading the spoiler log and selectively spoiling a location or item too.

**Comment by foxsouns** [comment]
the new owl items commit actually helps this :3
maybe we could do areas, too? a list per section of items you can add to..

**Comment by kbranch** [comment]
I'm not sure I follow - would the area thing be so that you can record hints for areas?

**Comment by foxsouns** [comment]
yeah! like, "hookshot is in tal tal", so you could optionally mark tal tal with hookshot so that you dont forget: i think these would do well in their own section, or maybe as a rightclick on the owl statue?

**Comment by kbranch** [comment]
Gotcha, that makes sense. It'll take some thinking about the UI - I have a few different things coming up soon that will require UI changes, so everything will need to mesh.

**Comment by kbranch** [comment]
I just put an initial pass at this up at https://dev.magpietracker.us/ if anybody wants to take a look.

The intention is to add support for selectively spoiling checks/items and for exporting the tagged checks as a plandomizer file - hence the complete item pool in the dropdown.

Autotracker support for marking seen items should be feasible too.

**Comment by foxsouns** [comment]
first impressions: clicking the check should add it to your item list (if applicable)

**Comment by kbranch** [comment]
This snowballed a bit, but I'm ready to call it done. I'm still not sure how to cleanly incorporate the hint support into the UI, but that can be addressed in #10.
