### ISSUE TITLE
[display/logic]: cross room logic

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#17]
adding this as an issue here so that we dont forget about actually doing something with it:

so, on my hard-logic entrance rando i am currently doing (`LhhsHTWRDKruEIl`, `B2D0F2DB5365690B38E9F709E4680225`, btw), i ended up at the main kanalet section with boomerang, but the tracker didnt list the boomerang ball&chain kill&grab from there. there's a few other cases that i dont know about, but there's rooms that deserve a double-check, kind of like how entrance enter/exit items work? click one and they both get checked.

**Comment by kbranch** [comment]
Good call, thanks!
