### ISSUE TITLE
[Enhancement] Different icon for owls

### ISSUE THREAD

**Issue by Llammissar** [kbranch/Magpie#19]
I wanted to turn owls on as a  visualreminder to myself that they have hints, but they show up as regular check dots and it ends up being confusing to me in practice.  So I'd like to request them get a different colour and maybe little ear tufts instead?

**Comment by foxsouns** [comment]
Owls have a setting in-randomizer to give extra items: that's why that flag turns them into checks. Could work as a hint-mode, added to the current mode, though.

**Comment by kbranch** [comment]
Nice, I like the idea of owls being displayed even when they don't give items. Should be pretty easy to do that and also style them differently than regular checks.

**Comment by kbranch** [comment]
Just pushed an update that shows owls as vanilla when not set to be checks and adds an admittedly ugly owl icon over top of them.
