### ISSUE TITLE
[dev-item branch]: Mermaid's Scale not listed, Necklace listed as Mermaid's Scale

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#22]
Setting the check to somewhere and collecting it reveals it just gives necklace: scale isn't even on the list.

**Comment by foxsouns** [comment]
![image](https://user-images.githubusercontent.com/60267141/208723789-75cf3a2e-af95-43bb-9ee2-2fc031e32ea2.png)

**Comment by kbranch** [comment]
Good catch, thanks! Should be fixed on the dev site now.
