### ISSUE TITLE
[dev-Enhancement]: Indoors (dungeon/cave/etc) cleared checks and unknown checks should not overlap

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#23]
I can provide a json if needed, but basically: when you have marked something and collected it, it should no longer show up in the overworld check map if there are more than one checks in that area. I have sword already in this.
![image](https://user-images.githubusercontent.com/60267141/208729675-adc97159-2e19-4302-ba88-4dad1502ff5b.png)

**Comment by foxsouns** [comment]
additional context, sorry
![image](https://user-images.githubusercontent.com/60267141/208730137-6dc47108-0f52-4597-b297-09dbbaab1756.png)

**Comment by kbranch** [comment]
You're right, the logic for that was too simple. Should be fixed now - it'll show an unchecked item if one exists, but checked items won't appear on the overworld node.

Overworld nodes with only a single check in them will still show the item they contained once checked. What do you think about that? I'm tempted to hide that once checked too, it's kind of hard to tell that it's checked for some items (like your heart piece screenshot)

**Comment by foxsouns** [comment]
I think if we reduced the size by maybe 3/4ths, or even just 7/8ths, it would allievate that difficulty to determine while not sacrificing legibility of the item: but single-checks would be something i would like to keep displayed, personally.

**Comment by kbranch** [comment]
Yeah, makes sense. I just tweaked the size, how's that look to you?

**Comment by foxsouns** [comment]
that looks pretty good: theyre pretty unambiguiously checked or not checked now, and the items arent perfect to see, but theyre not bad. maybe a an eighth/16th up?

**Comment by kbranch** [comment]
Ok, it's a little bigger now - I think I'll call it good
