### ISSUE TITLE
[QOL]: update inside area tooltip icons to LADX

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#29]
just bugs me a little bit: raft return does not require flippers, and mountain access has a boots crystal. oh, and the obvious color thing, yeah, but those are my two biggest nags with using the LA rooms.

**Comment by kbranch** [comment]
Yeah, makes sense - I just pushed an update with those two edited.

Taking fresh color screenshots would be nice, but it's more effort than it's worth to me, personally. I'd be happy to merge a pull request with them, though.
