### ISSUE TITLE
[Spoiler]: vanilla items are also unmarked

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#30]
replicated via goat reward in `hsHTWRl` `4B6846066452990082D9FEEEEFDD310F`

**Comment by kbranch** [comment]
I'm actually not sure I follow here - the goat reward populates correctly for me with this seed and settings, although it's not vanilla. I played around with it for a while and didn't find any issues with vanilla items, they all got spoiled correctly for me.

I did find and fix an issue where specifically the Yarna Desert rock seashell wouldn't get spoiled correctly, though.

**Comment by foxsouns** [comment]
that's.. weird as well, considering that i recall that one working.. i guess it all works now, though, so there's no issue? who knows: i use this tracker so frequently though that if something like this happens again, it's a 90% chance it'll happen to me, haha. closing for now, since.. apparently everything is working normally, i guess.

**Comment by foxsouns** [comment]
oh, that's an interesting bug! seems like the case; i think python incorporates time into it's prandomness, so which check it exports first in the spoiler could definitely shift.
