### ISSUE TITLE
[Null]: Simple connector causes null

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#31]
[Magpie-state-2023-01-06T21_37_02.722Z.json.zip](https://github.com/kbranch/Magpie/files/10363291/Magpie-state-2023-01-06T21_37_02.722Z.json.zip)
martha's bay cliff right side <-> outer rainbow cave right
(simple connector i am talking about)
(i dont need any fixed file, dont worry, backed out of this, just reporting it)

![image](https://user-images.githubusercontent.com/60267141/211105063-8d6bc5e6-2add-4773-958f-42f9f9fea60b.png)

**Comment by kbranch** [comment]
Oops, looks like a side effect of the fix for closing the dialog by clicking away from it. Just pushed a fix, thanks!
