### ISSUE TITLE
[Typo]: "Frong's Song of Soul" in item check-set right-click menu

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#32]
![image](https://user-images.githubusercontent.com/60267141/211130479-5d381334-6ce0-4850-8e43-f229f9bbe657.png)

(i would have pr'd this, but git couldnt find a "Frong" anywhere! might just be something i'm missing, or maybe something in `/ladxr`?)

**Comment by kbranch** [comment]
lol, good catch. I've fixed it in my local copy, I'll push it once I'm done with what I'm working on. I've also installed a spell checker extension, haha.

Also, it's here: https://github.com/kbranch/Magpie/blob/master/static/js/model/nodeTooltip.js#L102
