### ISSUE TITLE
[tracker]: banana sale not appearing

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#33]
not sure why, but banana sale isn't showing up on the map (however, it shows up in the checklist, and works there).
still using the `dev.` site.

tracker export: [Magpie-state-2023-01-12T17_53_24.587Z.json.zip](https://github.com/kbranch/Magpie/files/10404524/Magpie-state-2023-01-12T17_53_24.587Z.json.zip)
seed: `05E21E9D42FFB8B6CFEB855F6250F498`
short settings: `LgAghsHTWRrl`

**Comment by kbranch** [comment]
Thanks, looks like an issue with random start location when ER is off. Should be fixed now.
