### ISSUE TITLE
[null]: dungeon rando selection doesn't work

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#34]
using latest (/`dev.` site).
does not allow me to select using either the map or list "modes".

tracker state: [Magpie-state-2023-01-17T16_39_23.118Z.json.zip](https://github.com/kbranch/Magpie/files/10437366/Magpie-state-2023-01-17T16_39_23.118Z.json.zip)

**Comment by foxsouns** [comment]
entrance rando works, start rando works, this only happens when you have dungeon rando on, and entrance rando off. (start rando doesn't matter.)

**Comment by foxsouns** [comment]
tried to mitigate using the spoiler: right click stopped getting captured by the site afterwards, which is a definite sign of null tracker syndrome. sigh.

**Comment by foxsouns** [comment]
seed is `BAD9DC41FFE12F7D73B6603295CE63E1`. going to try to edit out the null and see if i can get a working tracker state again.

**Comment by foxsouns** [comment]
null at `customItems`, `customDungeonItems`, and `multiworld`. not sure if those are intended or not.

**Comment by kbranch** [comment]
Oops, looks like fallout from handling a different edge case. Just pushed a fix, I don't think the state should've gotten messed up from this.

**Comment by foxsouns** [comment]
changed multiworld to false: fixed it! now, why is it happening?

**Comment by foxsouns** [comment]
yeah, it works now: i thought i had fixed it before checking here haha

**Comment by kbranch** [comment]
Great, thanks for the report!
