### ISSUE TITLE
[tracker: dungeons]: double dungeons

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#35]
![image](https://user-images.githubusercontent.com/60267141/212969107-95473940-bb93-4987-8142-cf83b951eeed.png)
progressed a little bit, found color dungeon (at d5) and power bracelet, which unlocked color dungeon (vanilla check location) and...
i don't like how this is working. both of these function as the "main" check for d0, but that shouldn't work like that. i do like the "found at x" message, but there shouldn't be the whole checklist there on the non-main check (which, here, would be color dungeon: the "main" check is d5, which is where d0 is).

**Comment by kbranch** [comment]
Oh, yeah, that's not right. Looks like a similar problem to the last one you found. Just pushed a fix, thanks!
