### ISSUE TITLE
[null, entrance rando, spoiler]: "Spoil Entrance" on a connector cave breaks the other side

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#36]
experienced on `490804D44F3871464A32EA7353529CB4`, `LghsHTWRruEEl`, [state.zip](https://github.com/kbranch/Magpie/files/10448388/state.zip) (left of river cave <-> log cave mushroom side)

**Comment by kbranch** [comment]
Hmm, I'm having trouble reproducing this on my end. Which side did you spoil when the problem happened? Was the other side mapped at the time? If so, was it mapped by spoiling or manually?

Also, did you load the spoiler via the ROM or a JSON file? If the latter, could you post the file? I'm wondering if there's a difference between the JSON spoiler exported at generation time and the one created by dumping it from the ROM.

**Comment by foxsouns** [comment]
okay, sorry; i've figured out how to explain it, and it's a weird one.
reproduce it by having a valid connection between any two connector caves, and spoiling the entrance of one of them a second time.

however, specifically when done by spoiling the aforementioned river entrance twice, it throws an error (that i had overlooked earlier):
```
Traceback (most recent call last):
  File "/var/www/magpie/dev-Magpie/magpie.py", line 158, in renderCheckList
    logics = getLogics(args, entranceMap)
  File "/var/www/magpie/dev-Magpie/ladxrInterface.py", line 179, in getLogics
    log = logic.Logic(args, world_setup=worldSetup)
  File "/var/www/magpie/dev-Magpie/LADXR/logic/__init__.py", line 65, in __init__
    if world.indoor_location[indoor] is not None:
KeyError: None
```

oh, and i loaded the spoiler from rom.

**Comment by kbranch** [comment]
Perfect, thanks for figuring out what causes it! I just pushed a fix for it.
