### ISSUE TITLE
[Enhancement]: hover text for items on checklist

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#37]
for, well, mainly graphics packs, i guess. meme makes all the trading items hard to differentiate, but i like matching the graphics together with my rom regardless.. would be nice, not a huge priority, though.

**Comment by kbranch** [comment]
Yeah, makes sense. Should be pretty easy to do, the data should be there to generate a good tooltip automatically.

**Comment by kbranch** [comment]
I just pushed this to the dev site. I debated whether to use the LADXR names or to put in custom ones - it's the LADXR ones for now.

**Comment by foxsouns** [comment]
i think it hurts none to change the song titles, but the instrument names are something i like: if you were to change it, maybe something like "D1: Full Moon Cello"?

**Comment by foxsouns** [comment]
(i'm fond of having the dungeon it's from within the instrument name, i suppose)

**Comment by kbranch** [comment]
Yeah, I think that's a good call - should be live on the dev site now
