### ISSUE TITLE
[Visual]: embedded issues

### ISSUE THREAD

**Issue by foxsouns** [kbranch/Magpie#38]
![image](https://user-images.githubusercontent.com/60267141/213582384-29dc5b9a-2911-40af-bd2e-5769bbd29449.png)

... why does it think theyre all checked? tried resetting tracker state, no effect. happens on any random start setting.

**Comment by kbranch** [comment]
Yeah, sorry, that's from some other changes that I didn't test super well. The main site should be identical aside from these graphical issues and the item tooltips. I'll be pushing a fix for this specifically soon, but there are likely other related graphical problems.

**Comment by foxsouns** [comment]
in that case, i'll keep this open, and report any issues i see in use.

**Comment by kbranch** [comment]
Ok, this should be fixed on the dev site now. I'm not seeing any other graphical issues, but there probably still are some - I appreciate you keeping an eye out!

**Comment by foxsouns** [comment]
@kbranch found another one: landfill single entrance locations are missing the "checked" graphic.

**Comment by kbranch** [comment]
Got it, should be fixed - thanks!
