### ISSUE TITLE
Add a go mode indicator

### ISSUE THREAD

**Issue by kbranch** [kbranch/Magpie#8]
Ideally account for various goals as well.

**Comment by foxsouns** [comment]
for egg: what is all _actually_ required to defeat the boss? according to [the logic](https://github.com/daid/LADXR/blob/master/logic/requirements.py#L278), "d9" (i assume egg) boss is locked behind `OR(SWORD, BOW, MAGIC_ROD, BOOMERANG, HOOKSHOT)`: 
this, to me, means that:
- if we have all items logically needed to open egg, or have all needed items (for instruments-in-item-pool setting, or seashells); OR the requirement is no-egg
- have one of those d9 items
- can logically reach egg

we can enable a check for "winning" at the top: if you can see that check, it would basically be "go mode". the only goals here i cant wrap my head around are the bingo ones: they would require a bit of work, especially considering that i havent _actually played_ bingo mode yet, and dont know what the goals are.

**Comment by foxsouns** [comment]
okay, they seem easy enough to handle case-by-case.. just tedious to set up. wonder if there's logic checks in the rando for finishing goals...

**Comment by kbranch** [comment]
I think the D9 boss here is actually the Color Dungeon boss (Hardhit Beetle) - Color Dungeon is sometimes referred to as D0 and sometimes as D9.

I believe the egg boss's (Dethl) requirement is in the [overworld logic](https://github.com/daid/LADXR/blob/master/logic/overworld.py#L455): `AND(MAGIC_POWDER, SWORD, OR(BOOMERANG, BOW))`

But yeah, I think you're right that tying a check to that spot in logic is probably the best bet. That may be a little easier said than done, but it shouldn't be too bad.

Bingo is definitely a lot trickier. The board can in theory be read by the autotracker or imported from a spoiler log (after modifying LADXR to put the board in the spoiler log). The autotracker can also detect which goals are complete, but using logic to tell which goals are currently doable sounds like a daunting task. I'm not familiar enough with how the goals are incorporated into logic (if they even are - the "beatable" setting may not be compatible with bingo) to say how much work it would involve.

**Comment by foxsouns** [comment]
there's two ways i could see LADXR handling bingo:
- the game is generated as normal, and then some random bingo goals are added without regard to logic
- the game is generated with bingo goals in mind

and if i had to guess on it, i'd say the first: occam's razor. it makes this end of things kind of suck, though.

**Comment by kbranch** [comment]
Yeah, the first option seems to be my reading, unfortunately.

I see bingo_goals get set [here](https://github.com/daid/LADXR/blob/master/worldSetup.py#L123), then only ever referenced [here](https://github.com/daid/LADXR/blob/master/generator.py#L245), which just patches the ROM.

**Comment by kbranch** [comment]
Going to call this good enough for now since apparently LttP just made it a manual button. The egg has a logical icon that accounts for everything but bingo, and there's a manual button in the default dungeon item layout.
