### ISSUE TITLE
Show access to out of logic item pickups

### ISSUE THREAD

**Issue by kbranch** [kbranch/Magpie#9]
For example, winning powder from the Trendy Game, D0 pot, flying pickup in D2 pit maze room. Ideally, marking the node on the map would also mark the associated item

**Comment by Llammissar** [comment]
I noticed in a run the other day that flying pickups don't work to give you bombs if you haven't received them from a check already, is it different for powder?  (Trendy game DOES work for powder, though.  Used that this morning.)

**Comment by foxsouns** [comment]
Flying bombs do not work, however flying powder _does_ work.

**Comment by Llammissar** [comment]
Interesting, didn't expect that!  Thanks for clarifying.

**Comment by kbranch** [comment]
The backend framework for this is live on the [dev site](https://dev.magpietracker.us/), although no vanilla items have been added yet. Suggestions for which vanilla pickups should be included are welcome, I realized there are probably a lot more powder pickups than I can pull from the top of my head.

**Comment by kbranch** [comment]
I added all the powder pickups I knew of - feedback is welcome, but I'll close this now.
